version: '2'

services:

    cassandra1:
        image: kscape/docker-cassandra:latest
        container_name: cassandra1
        hostname: cassandra1
        environment:
            CASSANDRA_CLUSTER_NAME: docker-cassandra
        ports:
            - "7000"
            - "7001"
            - "7199"
            - "9042"
            - "9160"

    cassandra2:
        image: kscape/docker-cassandra:latest
        container_name: cassandra2
        hostname: cassandra2
        environment:
            CASSANDRA_SEEDS: cassandra1
            CASSANDRA_CLUSTER_NAME: docker-cassandra
        ports:
            - "7000"
            - "7001"
            - "7199"
            - "9042"
            - "9160"
        depends_on:
            - cassandra1

    cassandra3:
        image: kscape/docker-cassandra:latest
        container_name: cassandra3
        hostname: cassandra3
        environment:
            CASSANDRA_SEEDS: cassandra2
            CASSANDRA_CLUSTER_NAME: docker-cassandra
        ports:
            - "7000"
            - "7001"
            - "7199"
            - "9042"
            - "9160"
        depends_on:
            - cassandra2
